name: wpsandbox # Name must be unique for each app!
recipe: wordpress
config:
  php: '7.3'
  via: apache # Or nginx.
  database: mysql:5.7 # Or mariadb, etc.
  xdebug: true
  config:
    php: php.ini
services:
  mailhog:
    type: mailhog # Spin up a mailhog container called "mailhog".
    hogfrom: # Hog from appserver or nginx as appropriate.
      - appserver
  pma:
    type: phpmyadmin # Spin up a phpmyadmin container called "pma".
    hosts:
      - database
  ## Uncomment this section if needed for system/integration tests.
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
    #run_as_root:
    #  # Install subversion for running WP system tests.
    #  - "apt-get update && apt-get install subversion -y"
  #testdatabase:
  #  type: mysql
  #  creds:
  #    user: phpunit
  #    password: phpunit
  #    database: phpunit
tooling:
  install:wordpress:
    service: appserver
    cmd:
      - wp core download && wp config create --dbname=wordpress --dbuser=wordpress --dbpass=wordpress --dbhost=database
events:
  pre-stop:
    - echo "Backing up database..."
    - wp db export --path=/app - | gzip > /app/db_backup.sql.gz
    - echo "Database successfully backed up"
proxy:
  appserver:
    - wpsandbox.test
